CREATE TABLE campaign
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    total       DECIMAL,
    max         DECIMAL,
    image       text,
    CONSTRAINT pk_campaign PRIMARY KEY (id)
);

CREATE TABLE donate
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sol         DECIMAL,
    date_donate TIMESTAMP WITHOUT TIME ZONE,
    public_key  VARCHAR(255),
    campaign_id BIGINT,
    CONSTRAINT pk_donate PRIMARY KEY (id)
);

ALTER TABLE donate
    ADD CONSTRAINT FK_DONATE_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (id);